-- MySQL Script generated by MySQL Workbench
-- Mon Feb  2 00:52:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank_db` DEFAULT CHARACTER SET utf8 ;
USE `bank_db` ;

-- -----------------------------------------------------
-- Table `bank_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `street_address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomer`),
  UNIQUE INDEX `idcustomer_UNIQUE` (`idcustomer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_db`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`card` (
  `idcard` VARCHAR(16) NOT NULL,
  `pin` VARCHAR(60) NOT NULL,
  `login_attempts` TINYINT NOT NULL DEFAULT 0 COMMENT 'If locked, then 1',
  PRIMARY KEY (`idcard`),
  UNIQUE INDEX `idcard_UNIQUE` (`idcard` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_db`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`account` (
  `idaccount` VARCHAR(16) NOT NULL,
  `balance` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `account_type` ENUM('DEBIT', 'CREDIT') NOT NULL,
  `credit_limit` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `idowner` INT NOT NULL,
  PRIMARY KEY (`idaccount`),
  UNIQUE INDEX `idaccount_UNIQUE` (`idaccount` ASC) VISIBLE,
  INDEX `accoun.idowner-customer.idcustomer_idx` (`idowner` ASC) VISIBLE,
  CONSTRAINT `accoun.idowner-customer.idcustomer`
    FOREIGN KEY (`idowner`)
    REFERENCES `bank_db`.`customer` (`idcustomer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_db`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`transaction` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `idaccount` VARCHAR(16) NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `account-trancitions_idx` (`idaccount` ASC) VISIBLE,
  UNIQUE INDEX `idtransaction_UNIQUE` (`idtransaction` ASC) VISIBLE,
  CONSTRAINT `account-transictions`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bank_db`.`account` (`idaccount`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_db`.`card_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`card_account` (
  `idcard_account` INT NOT NULL AUTO_INCREMENT,
  `card_id` VARCHAR(16) NOT NULL,
  `account_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idcard_account`),
  INDEX `account-card_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `idcard_account_UNIQUE` (`idcard_account` ASC) VISIBLE,
  CONSTRAINT `card-card_account`
    FOREIGN KEY (`card_id`)
    REFERENCES `bank_db`.`card` (`idcard`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `account-card_account_debit`
    FOREIGN KEY (`account_id`)
    REFERENCES `bank_db`.`account` (`idaccount`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_db`.`account_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_db`.`account_customer` (
  `customer_id` INT NOT NULL,
  `account_id` VARCHAR(16) NOT NULL,
  `idaccount_customer` INT NULL AUTO_INCREMENT,
  INDEX `account-account_customer_idx` (`account_id` ASC) VISIBLE,
  PRIMARY KEY (`customer_id`, `account_id`),
  UNIQUE INDEX `idaccount_customer_UNIQUE` (`idaccount_customer` ASC) VISIBLE,
  CONSTRAINT `customer-account_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bank_db`.`customer` (`idcustomer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `account-account_customer`
    FOREIGN KEY (`account_id`)
    REFERENCES `bank_db`.`account` (`idaccount`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `bank_db` ;

-- -----------------------------------------------------
-- procedure customerData
-- -----------------------------------------------------

DELIMITER $$
USE `bank_db`$$
CREATE PROCEDURE customerData(in id INT)
BEGIN
SELECT 
idcustomer,
fname,
lname,
street_address,
city,
idaccount,
balance,
account_type,
credit_limit,
idowner
from account_customer ac
JOIN customer c on ac.customer_id=idcustomer
JOIN account a on ac.account_id=idaccount
WHERE idcustomer=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure accountData
-- -----------------------------------------------------

DELIMITER $$
USE `bank_db`$$
CREATE PROCEDURE `accountData` (in id char(16))
BEGIN
SELECT 
idaccount,
balance, account_type, credit_limit,
idowner, idcustomer, fname,
lname, street_address, city
from account_customer ac
JOIN customer c on ac.customer_id=idcustomer
JOIN account a on ac.account_id=idaccount
WHERE idaccount=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure withdraw
-- -----------------------------------------------------

DELIMITER $$
USE `bank_db`$$
CREATE PROCEDURE `withdraw` (
IN amount DECIMAL(15,2), IN account_id  CHAR(16))
BEGIN
DECLARE v_balance DECIMAL(15,2);
DECLARE v_type ENUM('CREDIT', 'DEBIT'); 
DECLARE v_limit DECIMAL(15,2);

IF amount < 0 THEN
	SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'NOSTO SUMMA EI VOI OLLA NEGATIIVINEN';
END IF;

SELECT balance, credit_limit, account_type 
INTO v_balance, v_limit, v_type
FROM account
WHERE idaccount=account_id
FOR UPDATE;
    
IF v_type IS NULL THEN
	SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'TILIÄ EI LÖYDY';
END IF;

CASE
	WHEN v_type = 'DEBIT' THEN
		IF v_balance >= amount THEN
			UPDATE account
			SET balance = balance - amount
			WHERE idaccount = account_id;
		ELSEIF v_balance < amount THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'KATE EI RIITÄ';
		END IF;
    
    WHEN v_type = 'CREDIT' THEN
		IF v_balance >= amount THEN
			UPDATE account
			SET balance = balance - amount
			WHERE idaccount = account_id;
		ELSEIF v_balance < amount THEN
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'LUOTTORAJA YLITTYY';
		END IF;
	END CASE;
END;$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure deposit
-- -----------------------------------------------------

DELIMITER $$
USE `bank_db`$$
CREATE PROCEDURE `deposit` (
IN amount DECIMAL(15,2), IN account_id CHAR(16))

BEGIN
DECLARE v_balance DECIMAL(15,2);
DECLARE v_type ENUM('CREDIT', 'DEBIT');

IF amount < 0 THEN
	SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'ET VOI TALLETTAA NEGATIIVISTA LUKUA';
END IF;

SELECT balance, account_type, credit_limit
INTO v_balance, v_type, v_limit 
FROM account 
WHERE idaccount = account_id
FOR UPDATE;


IF v_type IS NULL THEN
	SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'TILIÄ EI LÖYDY';
ELSEIF v_type = 'DEBIT' THEN
	UPDATE account SET balance= balance+amount
	WHERE idaccount = account_id;
ELSEIF v_type = 'CREDIT' THEN
		UPDATE account SET balance = balance+amount
        WHERE idaccount = account_id;
END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
