openapi: 3.0.0
info:
  title: Bank database API
  version: 1.0.0
  description: API documentation for a bank database
paths:
  /api/card:
    get:
      security:
      - bearerAuth: []
      tags:
        - Cards
      summary: Get all cards
      responses:
        '200':
          description: A list of cards
        '500':
          description: Server error
    post:
      security:
      - bearerAuth: []
      tags:
        - Cards
      summary: Create a new card 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idcard:
                  type: string
                pin:
                  type: string
      responses:
        '200':
          description: Card created
        '400':
          description: All required fields were not included in request body or card number was the same as another card
        '500':
          description: Server error
  /api/card/{idcard}:
    get:
      security:
      - bearerAuth: []
      tags:
        - Cards
      summary: Get card by ID
      parameters:
        - in: path
          name: idcard
          requider: true
          schema:
            type: string
          description: The card ID
      responses:
        '200':
          description: Card found, an empty list is returned if no cards were found
        '500':
          description: Server error
    put:
      security:
      - bearerAuth: []
      tags:
        - Cards
      summary: Update field for account by ID
      parameters:
        - in: path
          name: idcard
          required: true
          schema:
            type: string
          description: The card ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idcard:
                  type: string
                  description: New card ID
                  example: "newID"
      responses:
        '200':
          description: Card updated
        '400':
          description: All required fields were not included in request body 
        '404':
          description: Card not found
        '500':
          description: Server error
    delete:
      security:
      - bearerAuth: []
      tags:
        - Cards
      summary: Delete Card by ID
      parameters:
        - in: path
          name: idcard
          required: true
          schema:
            type: string
          description: The Card ID
      responses:
        '200':
          description: Card deleted
        '404':
          description: Card not found
        '500':
          description: Server error
  /api/card/{idcard}/accounts:
    get:
      security:
      - bearerAuth: []
      tags:
        - Cards
      summary: Get card accounts by card ID
      parameters:
        - in: path
          name: idcard
          requider: true
          schema:
            type: string
          description: The card ID
      responses:
        '200':
          description: List of accounts connected to the card
        '404':
          description: Card not found
        '500':
          description: Server error

