openapi: 3.0.0
info:
  title: Bank database API
  version: 1.0.0
  description: API documentation for a bank database
paths:
  /api/customer:
    get:
      security:
      - bearerAuth: []
      tags:
        - Customers
      summary: Get all customers
      responses:
        '200':
          description: A list of customers
        '500':
          description: Server error
    post:
      security:
      - bearerAuth: []
      tags:
        - Customers
      summary: Creates a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fname:
                  type: string
                lname:
                  type: string
                street_address:
                  type: string
                city:
                  type: string
      responses:
        '200':
          description: Customer created
        '400':
          description: All required fields were not included in request body
        '500':
          description: Server error
  /api/customer/{idcustomer}:
    get:
      security:
      - bearerAuth: []
      tags:
        - Customers
      summary: Get customer by ID
      parameters:
        - in: path
          name: idcustomer
          required: true
          schema:
            type: string
          description: The customer ID
      responses:
        '200':
          description: List of customers, an empty list is returned if no customers were found
        '500':
          description: Server error
    put:
      security:
      - bearerAuth: []
      tags:
        - Customers
      summary: Update all fields for customer by ID
      parameters:
        - in: path
          name: idcustomer
          required: true
          schema:
            type: string
          description: The customer ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fname:
                  type: string
                lname:
                  type: string
                street_address:
                  type: string
                city:
                  type: string
      responses:
        '200':
          description: Customer updated
        '400':
          description: All required fields were not included in request body 
        '404':
          description: Customer not found
        '500':
          description: Server error
    patch:
      security:
      - bearerAuth: []
      tags:
        - Customers
      summary: Update specific fields for customer by ID
      parameters:
        - in: path
          name: idcustomer
          required: true
          schema:
            type: string
          description: The customer ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                fname:
                  type: string
                lname:
                  type: string
                street_address:
                  type: string
                city:
                  type: string
      responses:
        '200':
          description: Customer updated
        '404':
          description: Customer not found
        '500':
          description: Server error
    delete:
      security:
      - bearerAuth: []
      tags:
        - Customers
      summary: Delete customer by ID
      parameters:
        - in: path
          name: idcustomer
          required: true
          schema:
            type: string
          description: The customer ID
      responses:
        '200':
          description: Customer deleted
        '404':
          description: Customer not found
        '500':
          description: Server error