openapi: 3.0.0
info:
  title: Bank database API
  version: 1.0.0
  description: API documentation for a bank database
paths:
  /api/transaction/account/{idaccount}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get transactions by account ID
      parameters:
        - in: path
          name: idaccount
          required: true
          schema:
            type: string
          description: The account ID
      responses:
        '200':
          description: A list of transactions. Can also be an empty list if account does not exist.
        '500':
          description: Server error
  /api/transaction/{idtransaction}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Get transaction by transaction ID
      parameters:
        - in: path
          name: idtransaction
          required: true
          schema:
            type: string
          description: The transaction ID
      responses:
        '200':
          description: A list of transactions
        '500':
          description: Server error
    put:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Update a transaction by ID
      parameters:
        - in: path
          name: idtransaction
          required: true
          schema:
            type: string
          description: The transaction ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idtransaction:
                  type: number
                idaccount:
                  type: string
                amount:
                  type: number
                date:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Transaction updated
        '400':
          description: All required fields were not included in request body
        '500':
          description: Server error
    patch:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Update specific fields of a transaction by ID
      parameters:
        - in: path
          name: idtransaction
          required: true
          schema:
            type: string
          description: The transaction ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idtransaction:
                  type: number
                idaccount:
                  type: string
                amount:
                  type: number
                date:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Transaction updated
        '500':
          description: Server error
    delete:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Delete a transaction by ID
      parameters:
        - in: path
          name: idtransaction
          required: true
          schema:
            type: string
          description: The transaction ID
      responses:
        '200':
          description: Transaction deleted
        '404':
          description: Transaction not found
        '500':
          description: Server error
  /api/transaction:
    post:
      security:
        - bearerAuth: []
      tags:
        - Transactions
      summary: Create a new transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idaccount:
                  type: string
                amount:
                  type: number
                date:
                  type: string
                  example: 2020-01-30 00:00:00
                description:
                  type: string
      responses:
        '200':
          description: Transaction created
        '400':
          description: All required fields were not included in request body
        '500':
          description: Server error
    
